Add early version of brief feature
drph4nt0m/avbot-v3 pull request #35
Opened 2020-10-11 01:31 UTC by ransbachm

# Preview. This will get cleaned up
Early version, mostly works. Debugging will later fully be removed.

Implemented like [old bot](https://github.com/drph4nt0m/avbot/blob/73ef652812c3979bfa947a6ccf7b2d4a0dfde493/bot.js#L2154
) and [this similar command](https://github.com/drph4nt0m/avbot-v3/blob/master/src/app/commands/weather/metar.js) for issue #11.

# Questions
There are some I thing I am not sure about read below. The issues should also be commented in the code (if not already solved).
- [ ] Is the name ```const *ivao* = require...``` right?
- [ ] In what command group does this belong in?
- [ ] Should colors (for example for error, or success in embedds) be centralised (like in old bot) or hard coded?
- [ ] Why does ```chart = await ivao.download(icao)``` alway return undefined? What am i doing wrong.
- [ ] Who should the error message look like (or should it just say unavailable like it is now)?

2020-10-11 08:29 UTC, drph4nt0m commented
@ransbachm 

1. Don't use moment-timezone package. For this project I am using dayjs. So change every implementation with dayjs
2. Use charts.ivao.aero for charts. Sample valid chart link: http://charts.avbot.in/VOMM.pdf
3. For getting chart link, create a new class and import it in brief.js 
4. For the footer of the message embed, concat both, see ivao command for example
5. Instead of calling catch on metar class call, surround it with try catch block and move the add field for metar inside the try of it.
6. Rename the class imports to be Capitalized (eg: Avwx, Ivao)
7. You don't need ivao class here.
8. Let the command group be weather itself.
9. Leave the colors as they are for now.

Let me know if you still have any doubts.

2020-10-11 12:50 UTC, ransbachm commented
- [ ] Don't use moment-timezone package. For this project I am using dayjs. So change every implementation with dayjs
- [ ] Use charts.ivao.aero for charts. Sample valid chart link: http://charts.avbot.in/VOMM.pdf
- [ ] For getting chart link, create a new class and import it in brief.js
- [ ] For the footer of the message embed, concat both, see ivao command for example
- [ ] Instead of calling catch on metar class call, surround it with try catch block and move the add field for metar inside the try of it.
- [ ] Rename the class imports to be Capitalized (eg: Avwx, Ivao)
- [ ] You don't need ivao class here.
- [ ] Let the command group be weather itself.
- [ ] Leave the colors as they are for now.

2020-10-13 15:29 UTC, ransbachm commented
Is the error message ok?

2020-10-14 17:48 UTC, drph4nt0m requested changes

2020-10-14 17:48 UTC, drph4nt0m commented on src/app/commands/weather/brief.js
> +          prompt: 'What ICAO would you like the bot to give METAR for?',
... to give briefing for?

2020-10-14 17:48 UTC, drph4nt0m commented on src/app/commands/weather/brief.js
> +    const timeform3 = Dayjs.utc().format('YYYY-MM-DD HH:mm:ss [Z]');
rename the varibale to zuluTime

2020-10-14 17:48 UTC, drph4nt0m commented on src/app/commands/weather/brief.js
> +      .setFooter(`${this.client.user.username} • Source: IVAO API`)
remove the source,, add "This is not a source for official briefing. Please use the appropriate forums." after the username .

2020-10-14 17:48 UTC, drph4nt0m commented on src/app/utils/Charts.js
> +module.exports = class Charts {
Rename the class to Chart, update the imports in other places as well

2020-10-14 17:48 UTC, drph4nt0m commented on src/app/utils/Charts.js
> +      return resolve(this.getChartURL(name));
add try catch, and if error/catch it should call reject

2020-10-17 04:30 UTC, drph4nt0m approved these changes

2020-10-17 04:30 UTC, merged

2020-10-17 04:31 UTC, drph4nt0m commented
@ransbachm thanks for your contribution. Feel free to take up other issues.

2020-11-01 06:05 UTC, drph4nt0m commented
@all-contributors please add @ransbachm for code